
version: '3.3'
services:
    elasticsearch:
        restart: always
        image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
        ports:
            - 9200:9200
            - 9300:9300
        environment:
            discovery.type: single-node
            http.cors.enabled: "true"
            http.cors.allow-origin: "*"
            ES_JAVA_OPTS: " -Xms256m -Xmx256m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - data01:/usr/share/elasticsearch/data
# Names our volume
volumes:
    my-db:
    data01:
        driver: local